# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/expo_db
spring.datasource.username=root
spring.datasource.password=

# API Keys 
github.classroom.token=YOUR_GITHUB_PAT_HERE
gemini.api.key=YOUR_GEMINI_API_KEY_HERE